/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pertemuan5;

import java.beans.PropertyVetoException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author mr_tech
 */
public class PenjualanRumah extends javax.swing.JFrame {

    /**
     * Creates new form PenjualanRumah
     */
    String database = "data_penjualan_rumah";
    String user = null;
    String password = null;
    String url = "jdbc:mysql://localhost:3306/";
    boolean dbExist = false;
    Connection connection = null;
    Statement statement = null;
    boolean aktifUser = false;
    public PenjualanRumah(){
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        barLogin = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        barPenjualanRumah = new javax.swing.JMenuItem();
        barTampilData = new javax.swing.JMenuItem();
        barCariData = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 844, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        barLogin.setText("Login");
        barLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barLoginActionPerformed(evt);
            }
        });
        jMenu1.add(barLogin);

        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Pilihan");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        barPenjualanRumah.setText("Penjualan Rumah");
        barPenjualanRumah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barPenjualanRumahActionPerformed(evt);
            }
        });
        jMenu2.add(barPenjualanRumah);

        barTampilData.setText("Tampil Data");
        barTampilData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barTampilDataActionPerformed(evt);
            }
        });
        jMenu2.add(barTampilData);

        barCariData.setText("Cari Data");
        barCariData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barCariDataActionPerformed(evt);
            }
        });
        jMenu2.add(barCariData);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barPenjualanRumahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barPenjualanRumahActionPerformed
        // TODO add your handling code here:
        if(this.aktifUser){
            MenuPenjualanRumah penjualan = new MenuPenjualanRumah(this);
            penjualan.setVisible(true);
            desktopPane.add(penjualan);
        }else{
            MenuLogin login = new MenuLogin(this);
            login.setVisible(true);
            StatusLogin keterangan = new StatusLogin("Anda Belum Melakukan Login", false, login , this);
            keterangan.setVisible(true);
            desktopPane.add(keterangan);
        }
    }//GEN-LAST:event_barPenjualanRumahActionPerformed

    private void barTampilDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barTampilDataActionPerformed
        // TODO add your handling code here:
        if(aktifUser){
            MenuTampilData tampilData;
            try {
                tampilData = new MenuTampilData(this);
                tampilData.setVisible(true);
                desktopPane.add(tampilData);
            } catch (SQLException ex) {
                Logger.getLogger(PenjualanRumah.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            MenuLogin login = new MenuLogin(this);
            login.setVisible(true);
            StatusLogin keterangan = new StatusLogin("Anda Belum Melakukan Login", false, login , this);
            keterangan.setVisible(true);
            desktopPane.add(keterangan);
        }
    }//GEN-LAST:event_barTampilDataActionPerformed

    private void barLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barLoginActionPerformed
        // TODO add your handling code here:
        MenuLogin login = new MenuLogin(this);
        login.setVisible(true);
        desktopPane.add(login);
    }//GEN-LAST:event_barLoginActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void barCariDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barCariDataActionPerformed
        // TODO add your handling code here:
        if(aktifUser){
            CariData frame;
            try {
                frame = new CariData(this);
                frame.setVisible(true);
                desktopPane.add(frame);
            } catch (SQLException ex) {
                Logger.getLogger(PenjualanRumah.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            MenuLogin login = new MenuLogin(this);
            login.setVisible(true);
            StatusLogin keterangan = new StatusLogin("Anda Belum Melakukan Login", false, login , this);
            keterangan.setVisible(true);
            desktopPane.add(keterangan);
        }

    }//GEN-LAST:event_barCariDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenjualanRumah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenjualanRumah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenjualanRumah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenjualanRumah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
            
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenjualanRumah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem barCariData;
    private javax.swing.JMenuItem barLogin;
    private javax.swing.JMenuItem barPenjualanRumah;
    private javax.swing.JMenuItem barTampilData;
    public javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
