/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package pertemuan4;

/**
 *
 * @author mr_tech
 */
public class Pemesanan extends javax.swing.JInternalFrame {

    /**
     * Creates new form Pemesanan
     */
    private final String namaKasir;
    private final String[][] pesanan = new String [3][3];
    private final MainMenu menu;
    public Pemesanan(String kasir, MainMenu menu) {
        initComponents();
        this.namaKasir = kasir;
        this.menu = menu;
        start();
    }
    
    private void start(){
        menu.aktif = this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        hitung = new javax.swing.JButton();
        bayarButton = new javax.swing.JButton();
        nasi = new javax.swing.JComboBox<>();
        ayam = new javax.swing.JComboBox<>();
        minum = new javax.swing.JComboBox<>();
        jumlahNasi = new javax.swing.JTextField();
        jumlahAyam = new javax.swing.JTextField();
        jumlahMinum = new javax.swing.JTextField();
        hargaNasi = new javax.swing.JTextField();
        hargaAyam = new javax.swing.JTextField();
        hargaMinum = new javax.swing.JTextField();
        bayarNasi = new javax.swing.JTextField();
        bayarMinum = new javax.swing.JTextField();
        bayarAyam = new javax.swing.JTextField();
        noMeja = new javax.swing.JTextField();
        totalBayar = new javax.swing.JTextField();

        jLabel1.setText("No. Meja");

        jLabel2.setText("jumlah");

        jLabel3.setText("Harga");

        jLabel4.setText("Total Bayar");

        jLabel5.setText("Total Pesanan");

        hitung.setText("OK");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });

        bayarButton.setText("Bayar");
        bayarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarButtonActionPerformed(evt);
            }
        });

        nasi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nasi", "Nasi Putih", "Nasi Goreng", "Nasi Capcay", " " }));
        nasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nasiActionPerformed(evt);
            }
        });

        ayam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ayam", "Ayam Goreng", "Ayam Bakar", "Ayam Penyet", " " }));
        ayam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayamActionPerformed(evt);
            }
        });

        minum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Minum", "Air Putih", "Jus Jeruk", "Jus Alpukat" }));
        minum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minumActionPerformed(evt);
            }
        });

        hargaNasi.setEditable(false);

        hargaAyam.setEditable(false);

        hargaMinum.setEditable(false);

        bayarNasi.setEditable(false);

        bayarMinum.setEditable(false);

        bayarAyam.setEditable(false);

        totalBayar.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(noMeja, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(minum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(ayam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(nasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jumlahMinum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumlahAyam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumlahNasi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hargaNasi, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(hargaAyam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hargaMinum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(bayarNasi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bayarAyam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bayarMinum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(hitung, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel4)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(bayarButton)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(totalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {hargaAyam, hargaMinum, hargaNasi});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ayam, minum, nasi});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(noMeja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hitung))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ayam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(minum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(hargaNasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hargaAyam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hargaMinum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(4, 4, 4)
                        .addComponent(jumlahNasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jumlahAyam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jumlahMinum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(bayarNasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bayarAyam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bayarMinum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5))
                    .addComponent(totalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bayarButton)
                .addGap(0, 28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private String paketNasi(){
        String harga = "";
        switch(nasi.getSelectedIndex()){
            case 0:
                harga = "0";
                break;
            case 1:
                harga = "5000";
                break;
            case 2:
                harga = "10000";
                break;
            case 3:
                harga = "12000";
                break;
        }
        return harga;
    }
   
    private String paketAyam(){
        String harga = "";
        switch(ayam.getSelectedIndex()){
            case 0:
                harga = "0";
                break;
            case 1:
                harga = "10000";
                break;
            case 2:
            case 3:
                harga = "17000";
                break;
        }
        return harga;
    }
    private String paketMinum(){
        String harga = "";
        switch(minum.getSelectedIndex()){
            case 0:
                harga = "0";
                break;
            case 1:
                harga = "3000";
                break;
            case 2:
            case 3:
                harga = "10000";
                break;
        }
        return harga;
    }
    private String[][] pesanan(){
        String pesan[][] = new String[4][3];
        
        pesan[0][0] = (String) nasi.getSelectedItem(); 
        pesan[0][1] = (String) ayam.getSelectedItem();
        pesan[0][2] = (String) minum.getSelectedItem(); 
        
        pesan[1][0] = jumlahNasi.getText(); 
        pesan[1][1] = jumlahAyam.getText(); 
        pesan[1][2] = jumlahMinum.getText(); 
        
        pesan[2][0] = hargaNasi.getText(); 
        pesan[2][1] = hargaAyam.getText(); 
        pesan[2][2] = hargaMinum.getText(); 
        
        pesan[3][0] = bayarNasi.getText(); 
        pesan[3][1] = bayarAyam.getText(); 
        pesan[3][2] = bayarMinum.getText(); 
        
        return pesan;
    }
    
    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // TODO add your handling code here:
        int bayarPaketNasi = Integer.parseInt(jumlahNasi.getText())  * Integer.parseInt(hargaNasi.getText());
        int bayarPaketAyam = Integer.parseInt(jumlahAyam.getText()) * Integer.parseInt(hargaAyam.getText());
        int bayarPaketMinum = Integer.parseInt(jumlahMinum.getText()) * Integer.parseInt(hargaMinum.getText());
        int totalPembayaran = bayarPaketNasi + bayarPaketAyam + bayarPaketMinum;
        bayarNasi.setText(Integer.toString(bayarPaketNasi));
        bayarAyam.setText(Integer.toString(bayarPaketAyam));
        bayarMinum.setText(Integer.toString(bayarPaketMinum));
        totalBayar.setText(Integer.toString(totalPembayaran));
    }//GEN-LAST:event_hitungActionPerformed

    private void nasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nasiActionPerformed
        // TODO add your handling code here:
        hargaNasi.setText(paketNasi());
    }//GEN-LAST:event_nasiActionPerformed

    private void bayarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        String nomerMeja = noMeja.getText();
        String totalPembayaran = totalBayar.getText();
        String[][] pesananPelanggan = pesanan();
        Pembayaran bayar = new Pembayaran(this.menu, nomerMeja, this.namaKasir, pesananPelanggan, totalPembayaran);
        bayar.setVisible(true);
        menu.desktopPane.add(bayar);
    }//GEN-LAST:event_bayarButtonActionPerformed

    private void ayamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayamActionPerformed
        // TODO add your handling code here:
        hargaAyam.setText(paketAyam());
        
    }//GEN-LAST:event_ayamActionPerformed

    private void minumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minumActionPerformed
        // TODO add your handling code here:
        hargaMinum.setText(paketMinum());
    }//GEN-LAST:event_minumActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ayam;
    private javax.swing.JTextField bayarAyam;
    private javax.swing.JButton bayarButton;
    private javax.swing.JTextField bayarMinum;
    private javax.swing.JTextField bayarNasi;
    private javax.swing.JTextField hargaAyam;
    private javax.swing.JTextField hargaMinum;
    private javax.swing.JTextField hargaNasi;
    private javax.swing.JButton hitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jumlahAyam;
    private javax.swing.JTextField jumlahMinum;
    private javax.swing.JTextField jumlahNasi;
    private javax.swing.JComboBox<String> minum;
    private javax.swing.JComboBox<String> nasi;
    private javax.swing.JTextField noMeja;
    private javax.swing.JTextField totalBayar;
    // End of variables declaration//GEN-END:variables
}
